### ISSUE TITLE
New device: LG G6

### ISSUE THREAD

**Issue by OpenDDR** [OpenDDRmobi/openddr-data#19]
http://www.lg.com/us/mobile-phones/g6?cmpid=social|G6|Diva2017|Upper|Twitter
UA: https://www.mylgphones.com/mysterious-lg-h700-smartphone-spotted-online.html

**Comment by keilw** [comment]
http://www.tera-wurfl.com/explore/?action=wurfl_id&id=lg_h870_ver1
