### ISSUE TITLE
New device: Asus ZenPad 10

### ISSUE THREAD

**Issue by keilw** [OpenDDRmobi/openddr-data#6]

**Comment by OpenDDR** [comment]
"user-agent":"Mozilla/5.0 (Linux; Android 6.0; P00C Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Safari/537.36",
"time_microseconds":1509,
"result":{"id":"genericAndroid

**Comment by keilw** [comment]
https://www.asus.com/de/Tablets/ASUS-ZenPad-10-Z300M/specifications/
